#!/bin/bash
#---------------------------para saber las IP esta up---------------------------------#
function is_alive_ping() {
  ping -c 1 $1 > /dev/null 2>&1
  [ $? -eq 0 ] && echo "Node with IP: $i is up."
  if ping -c 1 $1 > /dev/null 2>&1
  then
      host=$i
      firstport=20
      lastport=100
      echo "Puertos abiertos el IP $i:"
      portscan
  fi
}
#---------------------------para saber los puertos -----------------------------------#
function portscan {
for ((counter=$firstport; counter<=$lastport; counter++))
do
    (echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 && echo "$counter open"
done
}
#-----------------------para saber el sistema Operativo-------------------------------#
if type -t wevtutil &> /dev/null
then
    OS=MSWin
elif type -t scutil &> /dev/null
then
    OS=macOS
else
    OS=Linux
fi
echo "El Sistema operativo es: "$OS

for i in 192.168.100.{1..255}
do
is_alive_ping $i #& disown
done